### ISSUE TITLE
ur5 zip file missing

### ISSUE THREAD

**Issue by danielasun** [stack-of-tasks/pinocchio-tutorials#2]
In tutorial 1, the link to the zip file for the ur5 robot appears to be broken. Is there another place to find it?

**Comment by nmansard** [comment]
Thanks for the report. ZIP files are not properly installed by the CMakeFiles. @nim65s is currently implementing a fix. In the meantime, please see http://projects.laas.fr/gepetto/index.php/Teach/Supaero2018 for the html files manually corrected. In particular:
http://homepages.laas.fr/nmansard/teach/robotics2018/ur5.zip

**Comment by nim65s** [comment]
@nmansard: about this, could you check #1 ? :)

**Comment by danielasun** [comment]
Thank you! That seemed to work.
